### ISSUE TITLE
Today Widget

### ISSUE THREAD

**Issue by aaronpearce** [aaronpearce/DevSwitch#1]
Create a Today widget to show your favourite/recently used storefronts. Possibly could have a second widget to show your bookmarked apps.

**Comment by xjki** [comment]
In addition widget probably should show currently selected store.

**Comment by aaronpearce** [comment]
Sadly we have no way to know the currently selected store. We can only guess based on our last change which doesn’t mean it’s accurate

**Comment by xjki** [comment]
Got it. If recent switch is in the top of the widget it probably solves this as much as it's possible.
