### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by arkilis** [aaronpearce/DevSwitch#10]
**Describe the bug**
When following the steps on the README.md:

error: /Users/ben/ben_ws/mobile_dev/ios_dev/DevSwitch/Pods/Pods/Target Support Files/Pods-DevSwitch/Pods-DevSwitch.debug.xcconfig: unable to open file (in target "DevSwitch" in project "DevSwitch") (in target 'DevSwitch')

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1528028/54991009-be58e200-5007-11e9-8cdc-0d7145006169.png)

**Comment by aaronpearce** [comment]
Thanks for the report.

Based on the error logs, it looks like the Pods are incorrectly located somehow. In my local copy it correctly builds. Check the path set in the main project file for the configuration file.

**Comment by aaronpearce** [comment]
Going to close this due to lack of response. It seems to be a one-off issue. Please reopen if it still occurs after a clean clone.
