### ISSUE TITLE
Country change stopped working. It seems Apple changed URL scheme, and country switching stopped working...

### ISSUE THREAD

**Issue by luckyclan** [aaronpearce/DevSwitch#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aaronpearce** [comment]
@luckyclan Do you have the new URL scheme? 

Based on what I know, it is just broken in general with no replacement URL.

**Comment by luckyclan** [comment]
No, i couldn't find new url.m
Maybe Apple disabled it for some security/privacy reasons...

**Comment by aaronpearce** [comment]
Sadly not much to be done about this then. Just have to see if someone else in the community works it out.
