### ISSUE TITLE
Improve bootstrap script to ask or find local development team identifier

### ISSUE THREAD

**Issue by aaronpearce** [aaronpearce/DevSwitch#6]
Attempt to improve the bootstrap script to find or just ask for the user's local development team identifier to put into the codesigning setup for them

**Comment by shpakovski** [comment]
Hi Aaron, I hope this helps:

```bash
security find-certificate -c "Developer ID Application:" | grep "alis" | awk 'NF { print $NF }' | tr -d \(\)\"
```

**Comment by aaronpearce** [comment]
Thanks. Basic version is in PR #7 which is merged now.

I'd like to continue improving the error checking but for now I"m happy as a first step.
