### ISSUE TITLE
App Search doesn't find my app by name

### ISSUE THREAD

**Issue by Dschee** [aaronpearce/DevSwitch#9]
I just tried out this app (greay idea and thank you for sharing, by the way!) and wanted to add my Prayer app. Thus I opened the "Apps" tab and clicked the plus button on the top right. Then I searched for "Prayer" – but my app didn't show up. I also tried the exact name of the app in English and German (my default storefront) – being "Prayer in English" and "Gebet auf Deutsch" – but it couldn't find my app. Only searching for my account name "Cihat Guenduez" showed up my app.

Here's the US link to the app I'm talking about:
https://itunes.apple.com/us/app/prayer-in-english/id1217136884?mt=8

**Comment by aaronpearce** [comment]
Hey, just testing this out and it does return for me. App Search is a bit buggy in spots due to having no throttling on requests so sometimes it may misplace results right now.

**Comment by Dschee** [comment]
Actually, on first try searching for the developer account name didn't work either, but on a second try it did. So that's why. In any case, this doesn't seem to be a bug within DevSwitch then. Thanks for the quick answer!
